
<div class="container mt-5">
	<div class="row pt-4">
		
		<div class="col-md-3">

			<div class="perfil">
				<div class="perfilTopo">

				</div>

				<div class="perfilPainel">
					
					<div class="row mt-2 mb-2">
						<div class="col mb-2">
							<span class="perfilPainelNome"><?= $this->view->nome ?></span>
						</div>
					</div>

					<div class="row mb-2" id="painel-estatisticas">

						<div class="col">
							<span class="perfilPainelItem">Tweets</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->estatiscas['total_tweets'] ?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguindo</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->estatiscas['total_seguindo'] ?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguidores</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->estatiscas['total_seguidores'] ?></span>
						</div>

					</div>

				</div>
			</div>

		</div>

		<div class="col-md-6">
			<div class="row mb-2">
				<div class="col tweetBox">
					<form method="post" action="/tweet">
						<textarea class="form-control" required name="tweet" 
						  placeholder="Conte ao seus amigos sobre que você está pensando..." id="exampleFormControlTextarea1" rows="3"></textarea>
						
						<div class="col mt-2 d-flex justify-content-end">
							<button type="submit" class="btn btn-primary">Tweet</button>
						</div>

					</form>
				</div>
			</div>

			<? foreach ($this->view->tweets as $idx => $tweet) { 
				$dataHora = explode(" ", $tweet['data_formatada']);
				$tweet['data_formatada'] = $dataHora[0];
				$tweet['hora'] = $dataHora[1];
			?>

				<div class="row tweet">
					<div class="col-md-11 m-0 p-0">
						<p class="m-0 p-0"><strong class="text text-muted"><?= $tweet['nome'] ?></strong></p>
						<p class="content p-0 m-0"><?= $tweet['tweet'] ?></p>
						<button id="btn-verMais" class="btn btn-link btn-sm d-none toggle-btn">Ler mais</button>
					</div>

					<div class="col-md-1 p-0 text-center">
						<? if($tweet['id_user'] == $_SESSION['id']) { ?>
							<form method="post" action="/removerTweet?id=<?=$tweet['id'] ?>">
								<div>
									<button type="submit" class="btn btn-link" id="btn-trash">
										<small><i class="favorite far fa-trash-alt"></i></small>
									</button>
								</div>
							</form>
						<? } ?>
					</div>
				</div>

				<div class="row" style="pointer-events: none; margin-bottom: 50px;">
					<div class="col-md-10 p-0">
						<small>
							<span class="text tweetData">
								Data: <?= $tweet['data_formatada'] ?>
							</span>
						</small>
					</div>

					<div class="col-md-2 p-0 text-end">
						<small>
							<span class="text tweetHora">
								Hora: <?= $tweet['hora'] ?>
							</span>
						</small>
					</div>
				</div>

			<? } ?>

			<div class="row mt-5" style="margin-left: 25%;">
				<nav aria-label="...">
					<ul class="pagination">
						<li class="page-item <?= $this->view->pagina_ativa == 1 ? 'disabled' : '' ?>">
						   <a class="page-link" href="?pagina=1">Primeira</a>
						</li>

						<? for($i = 1; $i <= $this->view->total_paginas; $i++) { ?>
							<li class="page-item <?= $this->view->pagina_ativa == $i ? 'active' : '' ?>" aria-current="page">
								<a class="page-link" href="?pagina=<?= $i ?>"><?= $i ?></a>
							</li>
						<? } ?>

						<li class="page-item <?= $this->view->pagina_ativa == $this->view->total_paginas ? 'disabled' : '' ?>">
						   <a class="page-link" href="?pagina=<?= $this->view->total_paginas ?>">Última</a>
						</li>
					</ul>
				</nav>
			</div>
		</div>


		<div class="col-md-3">
			<div class="quemSeguir">
				<span class="quemSeguirTitulo">Quem seguir</span><br />
				<hr />
				<a href="/quem_seguir" class="quemSeguirTxt">Procurar por pessoas conhecidas</a>
			</div>
		</div>

	</div>
</div>
<script>
	document.querySelectorAll('.tweet').forEach(tweet => {
		const content = tweet.querySelector('.content');
		const button = tweet.querySelector('.toggle-btn');

		// Verifica se o texto está cortado
		function isTextOverflowing(el) {
			return el.scrollHeight > el.clientHeight;
		}

		if (isTextOverflowing(content)) {
			button.classList.remove('d-none');
		}

		button.addEventListener('click', () => {
			if (content.classList.contains('expanded')) {
				tweet.style = 'height: 140px;'
				content.classList.remove('expanded');
				button.innerText = 'Ler mais';
			} else {
				content.classList.add('expanded');
				tweet.style = 'height: auto;'
				button.innerText = 'Ver menos';
			}
		});
	});
</script>