<html>
	<head>
		<meta charset="utf-8" />
		<title>Twitter</title>

		<!-- bootstrap -->
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
		  integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

		<!-- font awesome -->
		<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>

		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">

		<link rel="stylesheet" type="text/css" href="/css/style.css">

		<link rel="shortcut icon" href="/img/twitter_logo.png" type="image/x-icon">

		<meta name="viewport" content="width=device-width, initial-scale=1.0">

	</head>

	<body>

		<nav class="navbar navbar-expand-lg menu">
			<div class="container-fluid m-2">
				<!-- Botão Hamburguer -->
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#menuHamburguer" 
					aria-controls="menuHamburguer" aria-expanded="false" aria-label="Alternar navegação">
					<small><span class="navbar-toggler-icon"></span></small>
				</button>

				<!-- Itens do Menu -->
				<div class="collapse navbar-collapse" id="menuHamburguer">
					<ul class="navbar-nav me-auto mb-2 mb-lg-0">
						<li class="nav-item align-self-center mt-1 ml-1">
							<a class="menuItem" href="/timeline">
								<button class="btn btn-primary">
									<span>Home</span>
								</button>
							</a>
						</li>
					</ul>

					<ul class="navbar-nav ms-auto">
						<li class="nav-item align-self-center mt-1 m-1">
							<a class="menuItem" href="/sair">
								<button class="btn btn-primary">
								<span>Sair</span>
								</button>
							</a>
						</li>
					</ul>
				</div>
				<img src="/img/twitter_logo.png" class="menuIco" />
			</div>
		</nav>

		<?= $this->content() ?>

		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
	</body>

</html>